dist: bionic
language: scala
jdk: openjdk11
if: tag IS blank
before_install:
- openssl aes-256-cbc -K $encrypted_682ff6f97e6e_key -iv $encrypted_682ff6f97e6e_iv
  -in private-key.pem.enc -out private-key.pem -d
- git fetch --tags
install:
- gpg --batch --import private-key.pem
stages:
- name: test
- name: release
  if: branch = master AND type = push
jobs:
  include:
  - stage: test
    script: sbt +test
  - stage: release
    script: sbt ciReleaseTagNextVersion ciReleaseSonatype
